### ISSUE TITLE
Editor is not defined

### ISSUE THREAD

**Issue by KrustyC** [draft-js-plugins/draft-js-plugins#1047] opened 2018-03-08 14:53 UTC
## Use-case/Problem

I get this error `editor is not defined ` on this [codesandox](https://codesandbox.io/s/1ylxj2rw2j).

I wanted to use it to report another issue, but I just found this

**Comment by freedomlang** [comment] 2018-03-08 16:16
@KrustyC i can not found the error you mention above in your codesandox, but i do found an error: 
<img width="467" alt="2018-03-09 00 11 43" src="https://user-images.githubusercontent.com/11409069/37161757-85262a8a-232e-11e8-99a1-dbb9a8447410.png">

this error was caused by accessing the wrong editor, and should be fixed by [this pr](https://github.com/draft-js-plugins/draft-js-plugins/pull/1040)

**Comment by KrustyC** [comment] 2018-03-14 12:51
for some reason the error I mentioned doesn't appear every time

**Comment by juliankrispel** [comment] 2018-03-18 17:18
Can't reproduce I'm afraid :)

**Closed by juliankrispel** 2018-03-18 17:18 UTC
