### ISSUE TITLE
Doesn't work Shift+Cmd+Left and Shift+Cmd+Right

### ISSUE THREAD

**Issue by hackerwins** [draft-js-plugins/draft-js-plugins#123] opened 2016-03-25 12:37 UTC
Thanks for your nice works. I started to use draft-js-plugins now.
I noticed `Shift+Cmd+Left` and `Shift+Cmd+Right` doesn't work after I used plugins.
I was digging the code and I found below code affect with key binding.

```javascript
if (command === undefined) {
  if (keyboardEvent.keyCode === 37 && KeyBindingUtil.hasCommandModifier(keyboardEvent)) {
    command = 'plugin-editor-move-to-start';
  } else if (keyboardEvent.keyCode === 39 && KeyBindingUtil.hasCommandModifier(keyboardEvent)) {
    command = 'plugin-editor-move-to-end';
  }
}
```
https://github.com/draft-js-plugins/draft-js-plugins/blob/6f5487ffa3b8a0f0f2abab611925c065363b6c56/draft-js-plugins-editor/src/Editor/index.js#L174

I don't know why this key bind is needed. How could we fixed the problem? I wish to help you If I can.

**Comment by nikgraf** [comment] 2016-03-26 05:28
Will look into this tomorrow or Sunday, thx for reporting

**Comment by okonet** [comment] 2016-03-26 09:39
This is the duplicate of #105

**Comment by nikgraf** [comment] 2016-04-20 05:14
Should be fixed now as we don't use any `contenteditable={ false }` in the new version. Can you verify this on the new documentation?

**Closed by nikgraf** 2016-04-20 05:14 UTC
Labels: bug, PR welcome
