### ISSUE TITLE
[mentions] Use a different trigger?

### ISSUE THREAD

**Issue by tleunen** [draft-js-plugins/draft-js-plugins#284] opened 2016-05-26 20:21 UTC
How hard would it be to allow multiple triggers for the mention plugins?

If you take a look at Facebook, it opens the suggestions box when you start writing `@`, but also when you type the entire firstname or lastname of a friend, or the first 5 characters of the first/lastname when the name is longer than that.

How hard would it be to support this? Or in a more general way, having some sort of custom trigger (regex maybe?).

**Comment by mjrussell** [comment] 2016-05-26 20:41
I think allowing for alternative methods for mention suggestions triggering would be pretty easy, you'd just want to expose the mentionSuggestionsSearch strategy into the config object here - https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/index.js#L103.

I think a more tricky piece would be having the suggestion strategy be dependent on the list of mentions themselves. if its just a static list that doesn't change, its pretty easy. But if you pass it down from props to the strategy (like you would when fetching the data from a server) then there isn't a good way (that I know of) to update the search strategy in response to a props change.

**Comment by tleunen** [comment] 2016-05-26 21:49
My `state.suggestions` might change over time, if that's what you mean.

**Comment by mjrussell** [comment] 2016-05-27 15:22
I think the problem is that the strategy as far as I have seen needs to be constant and not depend on `state.suggestions` while the filtering mechanism can do anything it wants, taking in the current value of the search. For instance you could easily set it up where the mentionSuggestionsStrategy kicks off on anything with `@` or words longer than some length of characters, but the strategy isn't the the thing that searches list mention list. Instead that is the responsibility of the suggestionFilter. If you don't have many other plugins it might not be the end of the world to make the suggestionStrategy be very greedy, but it could interfere with other plugins (say you have a linkify plugin it might treat long links as something for a suggestion and cause the link styling to disappear)

**Comment by mjrussell** [comment] 2016-05-27 15:23
Maybe @nikgraf has some ideas on strategies which can depend on a changing value?

**Comment by nikgraf** [comment] 2016-05-27 17:27
That’s indeed a bit tricky.

I think not having a strategy to match at all would work fine. The strategy right now helps to identify when to trigger a search. Then the `MentionsSuggestions` checks the current position, figures out the word for the current selection and triggers a search. It's all happening here:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L59-L139

I’m pretty confident with a few modifications it’s possible to do that. Keep in mind you better have your API endpoints cached 😛

**Comment by nikgraf** [comment] 2016-05-27 17:36
More in detail: Let’s look at the case where you have a collapsed selection that is inside a word. You get the position of the selection. Then walk through the characters to identify the start & end of the word. Spaces for example interrupt a word. Then you trigger a search for that word. On every state change (Selection or Content) you run it again.

**Comment by juliankrispel** [comment] 2017-09-26 22:42
just create a new plugin instance for every trigger you want to add...

Closing this issue, if you have a reason to keep it open please let me know

**Closed by juliankrispel** 2017-09-26 22:42 UTC
Labels: enhancement

**Comment by igorschoester** [comment] 2018-05-23 10:14
We have a use-case for two triggers that use the same character: `%` and `%%`. This currently does not work with two plugins instances.

**Comment by juliankrispel** [comment] 2018-05-23 10:18
@igorschoester I imagine that creates issues. What exactly is your usecase? Feel free to reach out on the draft js slack

**Comment by juliankrispel** [comment] 2018-05-23 11:32
you could just use your own `mentionRegExp` to control how the strategy
matches your symbols. That might do it for you.
