### ISSUE TITLE
The sticker plugin doesn't work on the demo website

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#383] opened 2016-08-06 07:35 UTC
I am unable to add a sticker here: https://www.draft-js-plugins.com/plugin/sticker

Clicking on one doesn't trigger anything apart form this error in the console:

```
app.js:3 Uncaught Error: Got unexpected null or undefinedn
  @ app.js:3value
  @ app.js:43_renderValidatedComponentWithoutOwnerOrContext
  @ app.js:38_renderValidatedComponent
  @ app.js:38_updateRenderedComponent
  @ app.js:38_performComponentUpdate
  @ app.js:38updateComponent
  @ app.js:38receiveComponent
  @ app.js:38receiveComponent
  @ app.js:6updateChildren
  @ app.js:38_reconcilerUpdateChildren
  @ app.js:39_updateChildren
  @ app.js:39updateChildren
  @ app.js:39_updateDOMChildren
  @ app.js:39updateComponent
  @ app.js:39receiveComponent
  @ app.js:38receiveComponent
  @ app.js:6updateChildren
  @ app.js:38_reconcilerUpdateChildren
  @ app.js:39_updateChildren
  @ app.js:39updateChildren
  @ app.js:39_updateDOMChildren
  @ app.js:39updateComponent
  @ app.js:39receiveComponent
  ...
```

**Comment by mzbac** [comment] 2016-08-09 04:59
that caused by blockReanderMap, because it  doesn't have 'sticker' blockTpye to map to element.
to solve this problem I think it needs to modify plugin-edit to support pass down blockReanderMap from plugins to draft-js

temporary fix can just add the below attribute in /docs/client/components/pages/Sticker/SimpleStickerEditor/index 's editor element
 blockRenderMap={DefaultDraftBlockRenderMap.merge(Map({'sticker':{ element: 'div'}}))}

**Comment by mzbac** [comment] 2016-09-13 22:12
I close this issue since it fixed by redeploy correct draftjs plugin version

**Closed by mzbac** 2016-09-13 22:12 UTC
Labels: bug
