### ISSUE TITLE
Multiple Mention editors conflict

### ISSUE THREAD

**Issue by tonypee** [draft-js-plugins/draft-js-plugins#298] opened 2016-06-08 05:44 UTC
I have a component which creates a mention simple mention component. It is standalone, and works fine.

When i iterate a list, and create multiple (i would be linking them to a list of rows) they conflict. When i @mention in the top componetn, the suggestions from the bottom component are displayed. then on arrow keys it disappears, never to show again. The only component to work in the last in the list (the corrosponding input to the suggestions that always show)

When i input after it is broken, i get the error: Uncaught TypeError: Cannot read property 'getIn' of undefined 

from 'MentionSuggestions' at the line: return editorState.getBlockTree(blockKey).getIn([decoratorKey, 'leaves', leafKey]);

Have you had issues with multiple components on the same page? (i realize that the example page has 2, but i dont see any options for id'ing them etc)

**Comment by nikgraf** [comment] 2016-06-08 06:52
Make sure to get a new plugin instance for every editor. More details here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors

**Comment by flgarrid** [comment] 2016-06-21 00:45
I'm getting the following error when I create a new instance of the plugin:

`React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`

It happens when I call the second suggestion: 
`const { EmojiSuggestions2  } = emojiPlugin2;`

Are you sure it is possible to create two instances?

**Comment by flgarrid** [comment] 2016-06-21 00:59
Ok so it seems that it's how Babel transpiles the definition of const.

If I declare the second variable as:

`const EmojiSuggestions2 = emojiPlugin2.EmojiSuggestions;`

It works fine.

**Comment by nikgraf** [comment] 2016-06-21 22:30
@flgarrid did you manage to get it work?

btw this is how JavaScript deconstruction works:

```JS
const emojiPlugin = {
  test: 2,
}

// works
const { test } = emojiPlugin;

// can't find test2
const { test2 } = emojiPlugin;
```

Does that help?

**Comment by flgarrid** [comment] 2016-06-22 13:31
@nikgraf Yup I solved it with my latest post.

The FAQ it has the following code:

```
const emojiPlugin = createEmojiPlugin();
const emojiPlugin2 = createEmojiPlugin();
const { EmojiSuggestions } = emojiPlugin;
const { EmojiSuggestions2 } = emojiPlugin2;
```

Which by what you described, won't work. 
Instead, it should be:

```
const emojiPlugin = createEmojiPlugin();
const emojiPlugin2 = createEmojiPlugin();
const { EmojiSuggestions } = emojiPlugin;
const EmojiSuggestions2= emojiPlugin2.EmojiSuggestions;
```

Thank you!

**Comment by tedlin182** [comment] 2016-06-24 23:14
I have the same issue. I created a stand-alone component for tagging users in comments and i am iterating a list of comments each with its own instance of this tagging component.

Unfortunately as I type in the usernames, the list doesn't render however when I add some console logs directly into the `MentionSuggestions` index.js file, it looks like it should be rendering the suggestions list.

The component is pretty much a copy of the Simple Example. Is there something I'm missing or need to adjust?

**Comment by tedlin182** [comment] 2016-06-25 23:22
Actually we found a way that works. Ended up creating a new plugin instance within the `constructor` of the component and assigned it to a property of the component. Then we were able to grab the `MentionSuggestions` component from that to render the list. This resolved the issue of iterating numerous instances of this component on our page:

```
  // MentionsComponent.jsx
  ...
  constructor(props) {
    super(props);

    this._mentionPlugin = createMentionPlugin();
  }

  render() {
    const { MentionSuggestions } = this._mentionPlugin;
    
    return (
      <div>
       ...
        <MentionSuggestions
          onSearchChange={ this.onSearchChange }
          suggestions={ this.state.suggestions }
        />
      </div>
    );
  }
```

**Comment by nikgraf** [comment] 2016-06-26 05:47
@flgarrid thx a lot for the hint, I just fixed the FAQ 🙌

@tedlin182 how did the code look like before? I'm curious to see if we can build in a warning, but I therefor I need to fully understand how you expected it to work 😊

**Comment by tedlin182** [comment] 2016-06-27 21:54
@nikgraf - So we created a new stand-alone component ( called `TaggableComponent`) using our slightly customized `Editor` along with the mentions plugin that we render with each `Comment` component we display on the page. This page typically renders at least 20 or so Comments at a time so we'll have many instances.

What we were expecting is that we could simply include this component within each `Comment` component and as it renders each comment, it would just create a new instance of our `TaggableComponent` and thus a new instance of the mention plugin.

Without the approach I pasted above, the mention suggestion list never appeared. For testing purposes, we only rendered 1 `Comment` component and thus 1 `TaggableComponent` and the list showed fine. We figured each instance of the component we rendered would create a new instance of the mentions plugin and only reference that instance, thus not creating any conflicts with other instances.

Does this make sense? We were hoping to just include the `MentionsSuggestion` component and that would be it.

**Comment by nikgraf** [comment] 2016-06-29 22:42
thanks! that definitely helps … We could make this happen, but I'm not sure we want to. Can't even imagine how complex the whole plugin would become & how many edge-cases & bugs we need to cover & fix. Will see 😄

**Comment by Zhouzi** [comment] 2016-06-30 11:05
IMHO creating a new instance and assigning it as a property of the component is the way to go. I do agree it can be surprising the first time but in the end that's how JavaScript closure work so it makes sense. I think the problem is that the documentation/examples are a bit miss leading since that's not what they're encouraging. Maybe we should update them to always instantiate the plugins in the constructor.

**Comment by jakegavin** [comment] 2017-03-16 23:27
I just ran into this and it took me a bit of searching to find this thread. Thanks for posting that solution (assigning the plugin instance to a property)! I think it'd be very helpful to update the documentation examples to follow that pattern or mention that each editor needs its own plugin instance. 

In retrospect, it feels obvious and I should've realized the problem sooner but as a new comer to the project, I was caught a little off guard when I ran into issues having multiple instances of my component that looked exactly like the one in the docs.

**Comment by nikgraf** [comment] 2017-03-21 08:06
@jakegavin we have it in the FAQ, but happy to add an example with multiple editors or another description. Can you open a PR so I can see what changed?

**Comment by davidsonsns** [comment] 2017-05-24 17:09
@tedlin182 you saved my life, I've been trying to solve it for hours.

**Comment by thomas88** [comment] 2017-09-11 10:31
Just ran into this issue myself and would appreciate to have it in the docs. Can you please add the pull request for your proposed changes @jakegavin?

**Comment by jakegavin** [comment] 2017-09-12 04:55
@thomas88 Sorry to hear you hit the same pain point and sorry to have not followed through on opening up a pr. 

PR is here: https://github.com/draft-js-plugins/draft-js-plugins/pull/869
I wasn't sure whether to change all the examples to use the property-based approach or add another example with multiple editors. Happy to change it to the latter if there is a downside to always assigning it to a class property.

**Comment by juliankrispel** [comment] 2017-09-26 22:44
thanks for the update to the docs @jakegavin 

I'm closing this issue, if you think this issue is still relevant please let us know why and we'll consider reopening it. Thank you for contributing ✌️

**Closed by juliankrispel** 2017-09-26 22:44 UTC
Labels: question

**Comment by LarsLiden** [comment] 2017-12-30 01:21
Still having issues with multiple instances on the same parent component, specifically, onSearchChange is only called for the last one I create.

My parent component, creates multiple instances like this:

                            .map(slot =>
                            {
                                return (
                                    <ChildComponent
                                        editorState={this.state.editorStates[slot.key] || EditorState.createEmpty()}
                                        key={slot.key}
                                        placeholder={''}
                                        onChange={eState => this.onChangeMentionEditor(eState, slot.key)}
                                    />
                                )
                            })

My ChildComponent is:

 constructor(p: Props) {
    super(p);
 
    this.mentionPlugin = createMentionPlugin({
        entityMutability: 'IMMUTABLE',
        mentionPrefix: mentionTrigger,
        mentionTrigger,
    })
  }

render() {
    const { MentionSuggestions } = this.mentionPlugin;

    return (
      <div>
          <Editor
            placeholder={this.props.placeholder}
            editorState={this.props.editorState}
            onChange={this.onChange}
            plugins={[this.mentionPlugin]}
            ref={this.setDomEditorRef}
            onFocus={this.onFocus}
            onBlur={this.onBlur}
            readOnly={this.props.disabled}
          />
          <MentionSuggestions
            onSearchChange={this.onSearchChange}
            suggestions={this.state.suggestions}
            entryComponent={CustomEntryComponent}
          />
        </div>
    )
  }

**Comment by zcapin** [comment] 2020-01-16 16:55
I know this is an old issue, didnt want to open another one, but i have the same issue, but my component is functional, new stuff came like hooks and i want to use it.

**Comment by mac-deviget** [comment] 2020-02-13 04:47
hello @zcapin 

I am using hooks to set a closure for the Editor but still not working.

I have a different problem, when I set the first state of the Editor, the Mentions plugin stop working

this is the code to initialize the editor with content

`useEffect(() => {
    const rawData = markdownToDraft(initialMarkdown, {
      preserveNewlines: true,
      remarkablePlugins: [RemarkableColorPlugin],
      blockStyles: {
        colored_open: 'colored_open',
      },
    })

    const contentState = convertFromRaw(rawData)
    const newEditorState = EditorState.createWithContent(contentState)
    setEditorState(newEditorState)
  }, [initialMarkdown])`

**Comment by dmay08** [comment] 2023-08-02 00:32
The solution is to memoize the 'createMentionPlugin' fx so that each iterated component has access to its own unique instance of the plugin:

const MyComponent = () => {

 const mentionPlugin = useMemo(() =>
        createMentionPlugin({
            theme: {...},
            mentionPrefix: '@',
            mentionPrefix: '@',
            mentionTrigger: '@',
            entityMutability: 'IMMUTABLE',
        }), [])
        
const { MentionSuggestions } = mentionPlugin
  
  return (
         <>
              <Editor
                    editorState={editorState}
                    onChange={onChange}
                    plugins={[ mentionPlugin]}
                />
                <MentionSuggestions
                    onSearchChange={onSearchChange}
                    suggestions={filteredUsers}
                    onAddMention={onAddMention}
                />
         </>
     )
 }
 
 export default MyComponent
