### ISSUE TITLE
react warning about extra porps

### ISSUE THREAD

**Issue by AndreyMiloserdov** [draft-js-plugins/draft-js-plugins#943] opened 2017-11-02 10:19 UTC
When create LinkifyPlugin plugin, react show warning:
![screen shot 2017-11-02 at 13 10 46](https://user-images.githubusercontent.com/26063680/32320661-97d554a2-bfcf-11e7-9af3-636c37febf12.png)
Packages dependency:
![screen shot 2017-11-02 at 13 14 04](https://user-images.githubusercontent.com/26063680/32320724-c3dc81f6-bfcf-11e7-8862-65994e1efa0e.png)

Code:

> import createLinkifyPlugin from 'draft-js-linkify-plugin';
>
> const linkifyPlugin = createLinkifyPlugin({ target: '_blank' });
>
>export default ([linkifyPlugin]);

Using:

> import draftJsPlugins from '../plugins/draft-js-plugins.config';
>
`<Editor
          placeholder={MESSAGE_PLACEHOLDER}
          plugins={draftJsPlugins}
          editorState={this.state.editorState}
          onChange={this.actions.onChange}
          keyBindingFn={this.actions.keyBindingFn}
          handleKeyCommand={this.actions.handleKeyCommand}/>`

**Comment by freedomlang** [comment] 2018-04-20 05:39
@AndreyMiloserdov Does the latest version have this problem?

**Comment by freedomlang** [comment] 2018-07-16 13:20
@AndreyMiloserdov Since we don't have enough info to reproduce this bug we'll need to close it. If you disagree please leave a comment and we'll take it from there.

**Closed by freedomlang** 2018-07-16 13:20 UTC
