### ISSUE TITLE
[draft-js-anchor-plugin] target="_blank" gets lost in contentState 

### ISSUE THREAD

**Issue by nareshbhatia** [draft-js-plugins/draft-js-plugins#1038] opened 2018-02-26 05:22 UTC
When using draft-js-anchor-plugin, I am setting the `linkTarget` option to `_blank` to set `target="_blank"`:

```
this.linkPlugin = createLinkPlugin({
    theme: {
        input: classes.input,
        inputInvalid: classes.inputInvalid,
        link: classes.link
    },
    linkTarget: '_blank'
});
```

This works well in the editor. When I inspect a link in the debugger, I can see the target:

```
<a
    class="TextEditBase-link-1060"
    title="http://archfirst.org"
    href="http://archfirst.org"
    target="_blank"
    rel="noopener noreferrer"
>
    <span data-offset-key="5uoh0-1-0"><span data-text="true">website</span></span>
</a>
```

However when I get the `contentState`, `target="_blank"` is not present in it. Here's how I iterate through the entities to see if the `target` attribute is present:

```
logEntities = () => {
    const contentState = this.state.editorState.getCurrentContent();
    const blocks = contentState.getBlocksAsArray();
    const totalBlocks = blocks.length;
    for (let i = 0; i < totalBlocks; i++) {
        const block = blocks[i];
        const text = block.getText();
        const charMetaList = block.getCharacterList();
        const entityPieces = getEntityRanges(text, charMetaList);
        entityPieces.map(([entityKey]) => {
            const entity = entityKey ? contentState.getEntity(entityKey) : null;
            const entityType = entity == null ? null : entity.getType().toUpperCase();
            console.log('entityType', entityType);
            if (entityType != null && entityType === ENTITY_TYPE.LINK) {
                console.log(entity);
            }
        });
    }
};
```

Here's a typical LINK entity as seen in the Chrome debugger. I don't see the target attribute in there. What am I missing?

![36654037-d3594e9e-1a87-11e8-9716-6b954be95c63](https://user-images.githubusercontent.com/1220198/36654446-c5404d78-1a8a-11e8-9121-858a11477880.png)

**Comment by arturchyzy** [comment] 2018-02-27 13:50
I think this is caused by not passing these additional information to entity creation. Take a look [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-anchor-plugin/src/utils/EditorUtils.js) 

`createLinkAtSelection(editorState, url) {
    const contentState = editorState.getCurrentContent()
      .createEntity('LINK', 'MUTABLE', { url });
    const entityKey = contentState.getLastCreatedEntityKey();
    const withLink = RichUtils.toggleLink(
      editorState,
      editorState.getSelection(),
      entityKey
    );
    return EditorState.forceSelection(
      withLink, editorState.getSelection()
    );
},`

**Comment by nareshbhatia** [comment] 2018-02-27 19:17
Thanks @arturchyzy, that sounds like the underlying problem.

**Comment by freedomlang** [comment] 2018-04-23 06:02
@nareshbhatia Would  you please offer a codesanbox ? It would be help for us to narrow down this issue

**Comment by juliankrispel** [comment] 2018-04-24 05:56
sounds like @arturchyzy has resolved this with you @nareshbhatia. I'm going to close this issue for now. If there are any further questions please let us know and we'll reopen

**Closed by juliankrispel** 2018-04-24 05:56 UTC
Labels: more info required
