### ISSUE TITLE
searchValue.toLowerCase is not a function after typing "@"

### ISSUE THREAD

**Issue by jbadger** [draft-js-plugins/draft-js-plugins#529] opened 2016-11-04 22:13 UTC
I am using the mentions plugin and followed the basic readme.  Whenever I type the @ sign, I get the following error in the console and no list of suggestions.  If I click into the field after the error, I then get the suggestions popup with my default suggestions list.

```
[Error] TypeError: searchValue.toLowerCase is not a function. (In 'searchValue.toLowerCase()', 'searchValue.toLowerCase' is undefined)
	defaultSuggestionsFilter (app.js:121767)
	onSearchChange (app.js:102107)
	onSearchChange
	onSearchChange (app.js:120901)
	onEditorStateChange (app.js:120867)
	(anonymous function) (app.js:119820)
	forEach
	onChange (app.js:119818)
	_update (app.js:111137)
	_update
	editOnBeforeInput (app.js:115419)
	(anonymous function) (app.js:110872)
	(anonymous function)
	dispatchEvent
	invokeGuardedCallback (app.js:14325)
	executeDispatch (app.js:14109)
	executeDispatchesInOrder (app.js:14132)
	executeDispatchesAndRelease (app.js:13554)
	forEach
	forEachAccumulated (app.js:14426)
	processEventQueue (app.js:13741)
	runEventQueueInBatch (app.js:21061)
	handleTopLevel (app.js:21072)
	handleTopLevelImpl (app.js:25690)
	perform (app.js:16738)
	batchedUpdates (app.js:25607)
	batchedUpdates (app.js:15400)
	dispatchEvent (app.js:25767)
	dispatchEvent
```

The error is happening here as it looks like it is expecting a string but is getting undefined.

```
var defaultSuggestionsFilter = function defaultSuggestionsFilter(searchValue, suggestions) {
  var value = searchValue.toLowerCase();
```

Versions:
```
    "draft-js": "^0.9.1",
    "draft-js-autolist-plugin": "0.0.3",
    "draft-js-linkify-plugin": "^2.0.0-beta5",
    "draft-js-mention-plugin": "^2.0.0-beta5",
    "draft-js-plugins-editor": "^2.0.0-beta5",
```

**Comment by MarinusDR** [comment] 2016-11-18 12:30
Yepp, i've got the same here.

**Comment by juliankrispel** [comment] 2017-09-28 17:53
can't reproduce this anymore, hence closing

**Closed by juliankrispel** 2017-09-28 17:53 UTC
