### ISSUE TITLE
[Mention Plugin] Uncaught TypeError in readonly mode with empty mention and mentionDecorator

### ISSUE THREAD

**Issue by oleksandraab** [draft-js-plugins/draft-js-plugins#1801] opened 2021-02-18 11:30 UTC
## Environment

- @draft-js-plugins/editor@4.1.0
- @draft-js-plugins/mention@4.2.0

## Description

Bug:
Trigger mention popup.
Either leave it empty or type a non-existing username. (eg. "some text @ more text" or "some text @randomname1234")
Safe text
Render text with readonly=true and mentionDecorator with mention styles
```
<Editor
                onChange={onChange}
                editorState={editorState}
                readOnly={true}
                decorators={mentionDecorator}
            />
```
Got Uncaught TypeError: props.store.getEditorState is not a function
![image](https://user-images.githubusercontent.com/73828700/108350172-2e684680-71e4-11eb-83dd-35089085c87e.png)

Expected behavior:
Mentions that can't be rendered display as plain text
Mentions that can be rendered display with styles from mentionDecorator

**Comment by fxOne** [comment] 2021-02-18 12:22
Can you provide a full reproducible demo as the [code]( https://github.com/draft-js-plugins/draft-js-plugins/blob/master/stories/mentions/src/SimpleMentionEditor.tsx )  from the storybook works for me? What kind of mentionDecorator are you using?

**Comment by oleksandraab** [comment] 2021-02-18 16:59
@fxOne thanks for a quick response.
after trying to reproduce it, I found out that if I add _plugins={[mentionPlugin]}_
making it:
`<Editor
                onChange={handleTextChange}
                editorState={editorState}
                readOnly={true}
                plugins={[mentionPlugin]}
                decorators={mentionDecorator}
            />`
instead of:
`<Editor
               onChange={onChange}
                editorState={editorState}
                readOnly={true}
                decorators={mentionDecorator}
            />`
it fixes my issue

**Comment by fxOne** [comment] 2021-02-24 11:13
@oleksandraab I guess we can close this issue?

**Closed** 2021-02-24 15:50 UTC
Labels: bug
