### ISSUE TITLE
Mention plugin. Mention wider than editor

### ISSUE THREAD

**Issue by busov** [draft-js-plugins/draft-js-plugins#980] opened 2017-11-26 11:42 UTC
When mention is long enough and takes more than one line of editor it also creates blank space highlighted with entity css. Is there a way to handle long entities to only highlight entity text on a new line? 
![image](https://user-images.githubusercontent.com/596592/33239664-4045a1fe-d2af-11e7-9c80-96f6d8396450.png)

**Comment by simsim0709** [comment] 2018-04-20 07:41
Hi, @busov 

Do you still have the problem? If so, can you provide reproduced demo, so that I can look into it.

Thanks.

**Comment by juliankrispel** [comment] 2018-04-25 23:55
@busov this is a css issue. You can just switch the style to use `inline` rather than `inline-block`. I'm going to close this issue for now since I believe it's answered. Cheers!

**Closed by juliankrispel** 2018-04-25 23:55 UTC
Labels: mentions-plugin, more info required
