### ISSUE TITLE
[mention plugin] Can I change the timing to find the mention?

### ISSUE THREAD

**Issue by DerekHung** [draft-js-plugins/draft-js-plugins#396] opened 2016-08-19 03:55 UTC
In mention-plugin
When we type "@" it will to find the match mention people
Can I delay the trigger till someone type any keyword?
like...

@ -> autocomplete will not trigger
@a -> autocomplete will trigger to find the match

Is there any way to make this thing happen?
or you will add a property to control this?
Thanks~

**Comment by Zhouzi** [comment] 2016-08-19 07:38
When the mention plugin starts matching a mention (e.g when typing "@") it calls `onSearchChange` with the value. From there, it's up to you to decide when you want to start looking for matches and display the suggestion. So if you don't want to match an empty query, you could:

```javascript
onSearchChange ({ value }) {
  if (value.length < 1) {
    return;
  }

  // do something else
}
```

Hope it helps ;)

**Comment by DerekHung** [comment] 2016-08-20 02:51
Thanks!!

**Comment by Zhouzi** [comment] 2016-08-20 08:59
I close this but feel free to get in touch if you have any further questions.

**Closed by Zhouzi** 2016-08-20 08:59 UTC
Labels: question

**Comment by DerekHung** [comment] 2016-08-26 08:20
@Zhouzi  sorry I guest it could work so I didn't test it till today
It has no effect to prevent match empty query
can you take a look for it?
thank you!

And there's another problem
Some Chinese input method would cause a fake input bar till you compose your input to a word
ex: enter 'wu' and press the return => '吳' 
so plugin will not to trigger the onSearchChange event, and there would be nothing to match
even if user has typing many words in Chinese like "@我愛你" => nothing happened

could you understand what I mean?

**Comment by Zhouzi** [comment] 2016-08-26 09:46
It doesn't prevent matching an empty query but when it does, you can prevent anything that could be caused by it. Why don't you want to match an empty query? Are you trying to avoid making unnecessary calls to an api? Then the solution above should work.

**Comment by didiaidada** [comment] 2017-04-27 05:47
@DerekHung  Did you solve this problem？ 
I am being troubled by this problem
