### ISSUE TITLE
[Mentions] cannot remove mention with backspace

### ISSUE THREAD

**Issue by alexkuz** [draft-js-plugins/draft-js-plugins#110] opened 2016-03-23 23:11 UTC
If I try to delete mention, this error occurs:
```
Uncaught Invariant Violation: Unknown DraftEntity key.
```

I'll try to create sample project later, if it's necessary.

**Comment by alexkuz** [comment] 2016-03-24 04:13
Can't reproduce it in sample - the problem might be something in my project. I'm not sure I'll have enough time to investigate this, so it's ok to close this issue for now.

**Comment by mxstbr** [comment] 2016-03-24 04:51
Thanks for getting back to us, will close this for now!

**Comment by nadimtuhin** [comment] 2016-03-25 13:38
I go the same problem :/ any clue?

**Comment by nikgraf** [comment] 2016-03-25 17:03
@nadimtuhin how to reproduce it?

**Comment by nadimtuhin** [comment] 2016-03-25 17:49
ok I am pushing it in a repo so you can check it.

**Comment by nikgraf** [comment] 2016-03-25 17:52
:+1: I reopened the issues

**Comment by alexkuz** [comment] 2016-03-25 18:03
@nikgraf oh, I just made sample project too :)

https://github.com/alexkuz/react-component-boilerplate/tree/temp-draft-js-mentions

**Comment by nadimtuhin** [comment] 2016-03-25 18:07
https://github.com/nadimtuhin/react-draft-js here is the repo. just do npm install and npm start

**Comment by nadimtuhin** [comment] 2016-03-25 18:21
[Archive.zip](https://github.com/draft-js-plugins/draft-js-plugins/files/189865/Archive.zip)

you can quickly view it uncompressing it

**Comment by Aleksion** [comment] 2016-03-30 14:24
As far as I can see the error seems to be reproduced in the sample: at least on my machine:
(Mac Ox El Capitan - chrome)

https://www.draft-js-plugins.com/plugin/mention

the error in the console is: ``Uncaught TypeError: Cannot read property 'start' of undefined``

**Comment by nikgraf** [comment] 2016-03-30 17:27
@Aleksion oh, thx for reporting. will work on a fix later today!

**Comment by nikgraf** [comment] 2016-04-05 04:35
Fixed it here: https://github.com/draft-js-plugins/draft-js-plugins/pull/180

thx again for reporting @Aleksion @alexkuz @nadimtuhin

**Closed by nikgraf** 2016-04-05 04:35 UTC
Labels: bug, In progress

**Comment by theuniverse** [comment] 2016-04-06 07:11
I met the same problem and now started with other guy's example as workaround. As I tried, the problem is in webpacked resources (bundle.js for me), and only happened with mention-plugin.

As is said above, the error is `Uncaught Invariant Violation: Unknown DraftEntity key.` But the root cause is there are 2 modules of "DraftEntity" in the project (one as top level module, another as nested module, which I don't know why :/ ) So creating and backspacing were jumping into different modules... the second copy (used by backspace) didn't know you've inserted an mention entity in the first one (used by mention-plugin). I will try to reproduce it again later.

**Comment by woodccc** [comment] 2016-10-17 07:31
I get the same error when selected mention,how to fix it ?

**Comment by MarkNijhof** [comment] 2016-10-18 11:33
Did anybody find out what was the cause of this? It is happening with my code now as well after I changed the way Webpack was configured

**Comment by MarkNijhof** [comment] 2016-10-18 12:35
Ok this is weird, I copied all the files for the editor locally and then it works perfectly, but as soon as I change the reference of the plugin editor to my own fork it fails in this way?

**Comment by woodccc** [comment] 2016-10-19 12:03
@MarkNijhof,I got this error too.As @theuniverse said 'the root cause is there are 2 modules of "DraftEntity" in the project'.My project had two modules.I find draft-js in 'draft-js-mention-plugin/node_modules' ,so, webpack build draft-js twice in bundle file.

You could update your draft-js as draft-js-mention-plugin use.
These are dependencies draft-js-mention-plugin used.
```
  "dependencies": {
    "decorate-component-with-props": "^1.0.2",
    "draft-js": ">=0.8.1",
    "find-with-regex": "^1.0.2",
    "immutable": ">=3.8.1",
    "lodash.escaperegexp": "^4.1.2",
    "react": ">=15.2.1",
    "react-dom": ">=15.2.1",
    "union-class-names": "^1.0.0"
  },
```
so, I update draft-js to '>=0.8.1'
```
"dependencies": {
    "antd": "2.0.1",
    "chai-shallow-deep-equal": "^1.4.4",
    "classnames": "2.2.0",
    "deep-equal": "1.0.1",
    "draft-js": ">=0.8.1",
   …
}
```

**Comment by MarkNijhof** [comment] 2016-10-19 15:29
Thanks will try this!

**Comment by Nihaux** [comment] 2016-10-19 15:50
I had the problem while working on a fork of the project. I had accidently run npm install in a plugin directory. 
There was two versions of draft-js: one in the root of the project, one in the plugin directory. 
So when I was creating a new entity in the /doc folder, it was creating an entity in the root draft-js library, and in the plugin it was trying to retrieve it from the local draft-js lib.
I just deleted the local node_modules (in the plugin dir) and it worked.

**Comment by MarkNijhof** [comment] 2016-10-19 19:49
Thanks @woodccc and @Nihaux that did it!

**Comment by gbbr** [comment] 2017-02-02 10:26
I get the same issue with AtomicBlocks, be it image or some other type of embedded media. This is with `draft-js@0.10.0` and I don't have other plugins conflicting dependencies.

```
invariant.js:44 Uncaught Error: Unknown DraftEntity key.
    at invariant (invariant.js:44)
    at Object.__get (DraftEntity.js:166)
    at ContentState.getEntity (ContentState.js:155)
    at MediaComponent (blockRenderer.jsx:30)
    at StatelessComponent.render (ReactCompositeComponent.js:44)
    at eval (ReactCompositeComponent.js:796)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
```

**Comment by yagneshmodh** [comment] 2017-02-02 13:00
When i am using image plugin with alignment focus and resize plugin i am getting following error. I am using draft-js version 0.10.0.

`index.js?d997:396 Uncaught Error: Unknown DraftEntity key.
    at invariant (eval at <anonymous> (main.js:600), <anonymous>:44:15)
    at Object.get (eval at <anonymous> (main.js:1050), <anonymous>:71:27)
    at Object.blockRendererFn (eval at <anonymous> (main.js:2718), <anonymous>:66:55)
    at eval (eval at <anonymous> (main.js:6246), <anonymous>:370:45)
    at DraftEditorContents.render (eval at <anonymous> (main.js:6306), <anonymous>:115:28)
    at eval (eval at <anonymous> (main.js:8790), <anonymous>:796:21)
    at measureLifeCyclePerf (eval at <anonymous> (main.js:8790), <anonymous>:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (main.js:8790), <anonymous>:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (eval at <anonymous> (main.js:8790), <anonymous>:822:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (eval at <anonymous> (main.js:8790), <anonymous>:746:36)`

**Comment by yagneshmodh** [comment] 2017-02-02 13:06
hello @gbbr i am getting the same error. Please let me know if you find any work arround.

**Comment by gbbr** [comment] 2017-02-02 13:37
Actually I posted this here by accident (sorry!). I had this link saved somewhere and I assumed it's an issue on the actual `draft-js` repo...

For me the solution was:
```js
    handleKeyCommand(command) {
        const {editorState, onChange} = this.props;
        const newState = RichUtils.handleKeyCommand(editorState, command);

        if (newState) {
            onChange(newState);
            return 'handled';
        }

        return 'not-handled';
    }
```
Hope this helps.

/cc @yagneshmodh
