### ISSUE TITLE
side-toolbar-plugin theming not supported?

### ISSUE THREAD

**Issue by williamli** [draft-js-plugins/draft-js-plugins#868] opened 2017-09-12 03:40 UTC
according to the docs, 

```
import buttonStyles from './buttonStyles.css';
import toolbarStyles from './toolbarStyles.css';
import blockTypeSelectStyles from './blockTypeSelectStyles.css';


const sideToolbarPlugin = createSideToolbarPlugin({
  theme: { buttonStyles, toolbarStyles, blockTypeSelectStyles }
});
```

I can customise the toolbar with css.

However, when I tried to provide a new size for .blockType

```
.blockType {
  box-sizing: border-box;
  border: 1px solid #ddd;
  background: #fff;
  padding: 5px;
  margin: 0;
  border-radius: 18px;
  cursor: pointer;
  height: 20px;
  width: 20px;
  line-height: 20px;
  text-align: center;
}
```

It the size of blockType is still 36px x 36px (default).

**Comment by juliankrispel** [comment] 2017-09-25 14:57
@williamli can you provide a [codesandbox](codesandbox.io) to reproduce the error

**Comment by freedomlang** [comment] 2018-05-01 15:59
@williamli Since we don't have enough info to reproduce this bug we'll need to close it. If you disagree please leave a comment and we'll take it from there.

**Closed by freedomlang** 2018-05-01 15:59 UTC
Labels: more info required
