### ISSUE TITLE
Emoji with selectButton param to open Emoji list?

### ISSUE THREAD

**Issue by EllisShen** [draft-js-plugins/draft-js-plugins#472] opened 2016-10-07 03:23 UTC
Is there a way to not using ":" (gamma) to open the Emoji Popover?  

I actually wish that all emoji icons can be shown up in a select list by manually clicking Button. Just like the Sticker plugin which provides an parameter of **SelectButton**. Is there any way to do it for Emoji?

**Comment by nikgraf** [comment] 2016-10-14 22:01
@EllisShen would be cool, I would be happy to merge a PR, but I'm too busy with other plugins to work on that right now.

will close this because it's a duplicate of https://github.com/draft-js-plugins/draft-js-plugins/issues/485

**Closed by nikgraf** 2016-10-14 22:01 UTC
