### ISSUE TITLE
Mention plugin working on fetch from server

### ISSUE THREAD

**Issue by andbet39** [draft-js-plugins/draft-js-plugins#184] opened 2016-04-06 14:29 UTC
i'm start working on the mod described in title. I' m new to react, not to javascript, world so i think is better to get some hint before making somenthing stupid. To fetch data over http do you think is better use axios or simple ajax fetch ?

**Comment by nikgraf** [comment] 2016-04-06 15:41
@andbet39 thx for your suggestion. This is not possible right now, but @cavneb will work on this today and we hope to cut a new release with this functionality built in soon.

I will close this issue for now as it is a duplicate of this: https://github.com/draft-js-plugins/draft-js-plugins/issues/155

If you have suggestions please feel free to join the discussion there :smile:

**Closed by nikgraf** 2016-04-06 15:41 UTC
