### ISSUE TITLE
Prefix not sent.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#380] opened 2016-08-03 12:19 UTC
How can i make it send the selected prefix when i use content.getPlainText(); the names are there, but not the actual prefix that has appeared in the input bar?

**Comment by Zhouzi** [comment] 2016-08-06 07:12
Are you referring to the mention plugin? Looks like you already submitted a similar issue, please see #264.

**Comment by Zhouzi** [comment] 2016-08-20 09:04
@stefan1968 I am closing as duplicate of #264 but let us know if the issues are not related.

**Closed by Zhouzi** 2016-08-20 09:04 UTC
Labels: question

**Comment by nikgraf** [comment] 2016-08-28 15:29
thx @zhouzi
