### ISSUE TITLE
Contributing Workflow

### ISSUE THREAD

**Issue by export-mike** [draft-js-plugins/draft-js-plugins#984] opened 2017-12-04 04:22 UTC
Hey,

I'm in the middle of creating a plugin, and notice the project has some repetitive changes regarding local requires within the repo, publishing and building the project.

Just a thought has anyone tried using lerna with this project? If so were there issues? 

Otherwise I'm keen to contribute a PR with updated config. let me know if you think this will be useful.

Cheers,

**Comment by freedomlang** [comment] 2018-04-19 10:10
Duplicate of #282

**Comment by juliankrispel** [comment] 2018-04-25 23:50
@export-mike I have been thinking about lerna, would be nice to have a nicer workflow for managing the project, if you'd still like to discuss feel free to reach me on the draft js slack ♥️

**Closed by juliankrispel** 2018-04-25 23:50 UTC
Labels: duplicate
