### ISSUE TITLE
SearchSuggestions position is not working properly when inside an overflowing div

### ISSUE THREAD

**Issue by Aleksion** [draft-js-plugins/draft-js-plugins#206] opened 2016-04-18 14:44 UTC
I'm not sure where exactly the issue is happening, but the SearchSuggestions PopOver's location doesn't seem to be working inside my overflowing scrollable div. The previous version of the mention plugin worked just fine position wise though. I'd like to debug it myself, but I can't quite wrap my head around the current position logic - and any click event (even ones occuring in chrome's console), dismisses the popover again. 

![screeenshot](https://cloud.githubusercontent.com/assets/3367641/14608135/c0b038bc-0584-11e6-843f-f281705c85e3.png)

**Comment by nikgraf** [comment] 2016-04-18 15:42
oh, thx for reporting @Aleksion 👍 

Seems like I didn't to the positioning properly. I will play with it & try to fix it. btw the position logic is here in case you have time to debug: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/SearchSuggestions/index.js#L42

 Can you elaborate a bit more on: "and any click event (even ones occuring in chrome's console), dismisses the popover again." Maybe a gif or video to demonstrate the issue?

**Comment by nikgraf** [comment] 2016-04-18 15:43
@Aleksion btw I still haven't forgotten your other requests 😄 sorry, other stuff was more important to fix first …

**Comment by nikgraf** [comment] 2016-04-20 06:08
@Aleksion I tried to put it into a div with `overflow-y: scroll; height:400px;`, but couldn't reproduce the issue. Can you create a working gist or so?

**Comment by wbf1013** [comment] 2016-05-08 12:04
I also have this problem, becasue of parent element have style of  `position:relative`  ,then the SearchSuggestions move other position!
<img width="500" alt="_20160508200317" src="https://cloud.githubusercontent.com/assets/1181144/15097737/f4d82540-1557-11e6-8e84-b931c00fcda4.png">

**Comment by nikgraf** [comment] 2016-05-08 23:11
@wbf1013 thx for investigating! That makes a lot of sense now. Ideally we could update [this function](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/utils/positionSuggestions.js) to make it work with `position: relative`.

Anyone interested to fix this?

**Comment by mjrussell** [comment] 2016-05-14 01:13
@wbf1013 @nikgraf 

FYI here is come code I recently used to get the position absolute with respect to the parent (to work with relative or scrollable containers). Im not sure exactly how we could implement this generically to work because it is dependent on the parent. Maybe using a document selector is good enough but seemed kind of hacky. But if you render it inside the component you can do this:

```js
  /**
   * returns the inline styles for the suggestion component to align it correctly with the completion
   * because this item scrolls, we need to absolutely position it to the parent
   */
  getPositionSuggestions = ({ decoratorRect, state, props }) => {
    const wrapperRect = this.refs.editorWrapper.getBoundingClientRect();
    const left = decoratorRect.left - wrapperRect.left;
    const top = decoratorRect.top - wrapperRect.top;

    let transform;
    let transition;

    if (state.isActive & props.suggestions.size > 0) {
      transform = 'scale(1)';
      transition = 'all 0.25s cubic-bezier(.3,1.2,.2,1)';
    } else if (state.isActive) {
      transform = 'scale(0)';
      transition = 'all 0.35s cubic-bezier(.3,1,.2,1)';
    }

    return {
      position: 'absolute',
      left: `${left}px`,
      top: `${top}px`,
      transform,
      transformOrigin: '1em 0%',
      transition,
    };
  };
```

**Comment by juhaelee** [comment] 2016-05-25 15:05
@nikgraf I'm a little confused as to how the decoratorRect is being created. I see that from [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/8bbede663a020e96b10d51d9445d380242cc9504/draft-js-mention-plugin/src/MentionSuggestions/index.js#L41) that it called `this.props.store.getPortalClientRect`, but all that function is doing is returning [a value from a map](https://github.com/draft-js-plugins/draft-js-plugins/blob/90eeb2362b8b1b9353adaeb6c055535b1083dd13/draft-js-mention-plugin/src/index.js#L51)? Where is the actual calculation being done?

**Comment by mjrussell** [comment] 2016-05-25 15:32
@juhaelee I think the value for the portalClientRect is set here - https://github.com/draft-js-plugins/draft-js-plugins/blob/90eeb2362b8b1b9353adaeb6c055535b1083dd13/draft-js-mention-plugin/src/MentionSuggestionsPortal/index.js#L21

**Comment by vinhlh** [comment] 2016-06-04 09:33
@mjrussell how do you set `refs.editorWrapper` in that context?

So, it's a possible solution that we can force the parent editor always to be `relative`, and calculate the mentionSuggestion layout by your way.

**Comment by vinhlh** [comment] 2016-06-04 10:40
@mjrussell  how to get `editorWrapper` in that context?

**Comment by nikgraf** [comment] 2016-06-19 21:46
fixed with https://github.com/draft-js-plugins/draft-js-plugins/pull/309

**Closed by nikgraf** 2016-06-19 21:46 UTC
Labels: bug, PR welcome
